version: '3.9'

services:
  user_app:
    container_name: user_app
    image: candea/user_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/Electrica
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      PG_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: Electrica
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

